---

- name: Install kubernetes and Flannel
  yum:
      name: "{{item}}"
      state: present
  with_items:
    - "{{kubernetes_node_install_list}}"

- name: Config kubernetes
  template: src="{{item}}" dest={{kube_config_path}} mode=644
  with_items:
    - "{{kubernetes_config_file_list}}"

- name: Config Docker
  template: src=docker dest={{sys_config_path}} mode=644
  
- name: Add docker accelerator
  template: src=daemon.json dest=/etc/docker
  when: accelerator

- name: Config Flannel
  template: src=flanneld dest={{sys_config_path}} mode=644

- name: Restart Docker and Flannel Serivce
  systemd:
    name: "{{item}}"
    state: restarted
    enabled: yes
  with_items:
    - 'flanneld'
    - 'docker'


- name: Stop Firewalld
  systemd:
    name: 'firewalld'
    state: stopped
    enabled: no
  ignore_errors: true


- name: Start Kubernetes Node
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  with_items:
    - 'kubelet'
    - 'kube-proxy'
